# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-Present Intel Corporation

name: Build and Push image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push new BESS base image
        run: yes y | ./env/rebuild_images.py focal64
